version: '3.8'
services:
  couchbase:
    image: couchbase:7.2.3
    container_name: couchbase
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    environment:
      - COUCHBASE_USERNAME=Administrator
      - COUCHBASE_PASSWORD=password
    volumes:
      - cb_data:/opt/couchbase/var
volumes:
  cb_data:
